export const SET_VIN_CODE = 'SET_VIN_CODE';
export const SET_PART_NAME_LIST = 'SET_PART_NAME_LIST';
export const SET_CAR_MODEL_LIST = 'SET_CAR_MODEL_LIST';
export const SET_PART_CATEGORY_LIST = 'SET_PART_CATEGORY_LIST';
export const SET_PART_LIST = 'SET_PART_LIST';
export const SET_CAR_MODEL_ID = 'SET_CAR_MODEL_ID';
